sudo: required

#env:
#  - VERSION="0.0.1"

services:
  - docker

before_install:
#  - docker build -t quay.io/CRI-iAtlas/irwg-tool-mitcr:${VERSION} .
#  - pip2.7 install --user setuptools==28.8.0

install:
  - pip2.7 install --user cwl-runner cwltool==1.0.20170217172322 schema-salad==2.2.20170222151604 avro==1.8.1

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
#  - cwltool --non-strict Dockstore.cwl test.cwl.json
